import type { SchedulerSnapshot } from "@/lib/types";

export const demoSchedulerSnapshot: SchedulerSnapshot = {
  month: "2026-03",
  productionUnits: [
    {
      id: "unit-casting",
      name: "Casting Hall",
      description: "High-throughput production line with rotating post coverage.",
    },
    {
      id: "unit-dispatch",
      name: "Dispatch Yard",
      description: "Outbound flow with dock, scale, and release coverage.",
    },
  ],
  competencies: [
    { id: "comp-post-1", unitId: "unit-casting", code: "Post 1", label: "Furnace feed", colorToken: "amber" },
    { id: "comp-post-11", unitId: "unit-casting", code: "Post 11", label: "Mold prep", colorToken: "teal" },
    { id: "comp-post-12", unitId: "unit-casting", code: "Post 12", label: "Pour line", colorToken: "violet" },
    { id: "comp-post-21", unitId: "unit-casting", code: "Post 21", label: "Quality bay", colorToken: "rose" },
    { id: "comp-dock-2", unitId: "unit-dispatch", code: "Dock 2", label: "Scale + manifest", colorToken: "blue" },
    { id: "comp-dock-7", unitId: "unit-dispatch", code: "Dock 7", label: "Release gate", colorToken: "lime" },
    { id: "comp-dock-9", unitId: "unit-dispatch", code: "Dock 9", label: "Outbound staging", colorToken: "orange" },
  ],
  teams: [
    {
      id: "team-orbit",
      unitId: "unit-casting",
      name: "Orbit Crew",
      description: "Primary melt team anchored to the 601/602 rotation.",
      accentColor: "#f97316",
      employees: [
        {
          id: "emp-ava",
          name: "Ava Patel",
          role: "Senior Operator",
          teamId: "team-orbit",
          scheduleCode: "601",
          rotationAnchor: 0,
          competencyIds: ["comp-post-1", "comp-post-11", "comp-post-12"],
        },
        {
          id: "emp-noah",
          name: "Noah Kim",
          role: "Relief Operator",
          teamId: "team-orbit",
          scheduleCode: "602",
          rotationAnchor: 1,
          competencyIds: ["comp-post-11", "comp-post-21"],
        },
        {
          id: "emp-jules",
          name: "Jules Martin",
          role: "Coordinator",
          teamId: "team-orbit",
          scheduleCode: "603",
          rotationAnchor: 2,
          competencyIds: ["comp-post-12", "comp-post-21"],
        },
        {
          id: "emp-mika",
          name: "Mika Stone",
          role: "Operator",
          teamId: "team-orbit",
          scheduleCode: "604",
          rotationAnchor: 3,
          competencyIds: ["comp-post-1", "comp-post-12"],
        },
      ],
    },
    {
      id: "team-anchor",
      unitId: "unit-casting",
      name: "Anchor Crew",
      description: "Coverage team balancing day and night runs across the hall.",
      accentColor: "#0f766e",
      employees: [
        {
          id: "emp-siena",
          name: "Siena Morales",
          role: "Team Lead",
          teamId: "team-anchor",
          scheduleCode: "601",
          rotationAnchor: 4,
          competencyIds: ["comp-post-1", "comp-post-21"],
        },
        {
          id: "emp-owen",
          name: "Owen Clarke",
          role: "Operator",
          teamId: "team-anchor",
          scheduleCode: "602",
          rotationAnchor: 5,
          competencyIds: ["comp-post-11", "comp-post-12"],
        },
        {
          id: "emp-rina",
          name: "Rina Das",
          role: "Utility Relief",
          teamId: "team-anchor",
          scheduleCode: "603",
          rotationAnchor: 6,
          competencyIds: ["comp-post-11", "comp-post-12", "comp-post-21"],
        },
        {
          id: "emp-teo",
          name: "Teo Ramirez",
          role: "Operator",
          teamId: "team-anchor",
          scheduleCode: "604",
          rotationAnchor: 7,
          competencyIds: ["comp-post-1", "comp-post-12"],
        },
      ],
    },
    {
      id: "team-vector",
      unitId: "unit-dispatch",
      name: "Vector Crew",
      description: "Outbound team for dock release, dispatch staging, and manifests.",
      accentColor: "#2563eb",
      employees: [
        {
          id: "emp-cam",
          name: "Cam Russell",
          role: "Dispatch Lead",
          teamId: "team-vector",
          scheduleCode: "601",
          rotationAnchor: 8,
          competencyIds: ["comp-dock-2", "comp-dock-7"],
        },
        {
          id: "emp-lena",
          name: "Lena Abbas",
          role: "Yard Specialist",
          teamId: "team-vector",
          scheduleCode: "602",
          rotationAnchor: 9,
          competencyIds: ["comp-dock-7", "comp-dock-9"],
        },
        {
          id: "emp-eli",
          name: "Eli Foster",
          role: "Coordinator",
          teamId: "team-vector",
          scheduleCode: "603",
          rotationAnchor: 10,
          competencyIds: ["comp-dock-2", "comp-dock-9"],
        },
        {
          id: "emp-zara",
          name: "Zara Shah",
          role: "Relief Operator",
          teamId: "team-vector",
          scheduleCode: "604",
          rotationAnchor: 11,
          competencyIds: ["comp-dock-2", "comp-dock-7", "comp-dock-9"],
        },
      ],
    },
  ],
  assignments: [],
};
